name: upayza
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  retrofit: ^4.4.1
  dio: ^5.7.0
  built_value: ^8.9.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.3
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2
  iconly: ^1.0.1
  intl: any
  intl_utils: ^2.8.7
  flutter_svg: ^2.0.16
  pinput: ^5.0.0
  url_launcher: ^6.3.1
  go_router: ^14.6.2
  image_picker: ^1.1.2
  firebase_core: ^3.8.1
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  awesome_extensions: ^2.0.19
  connectivity_plus: ^6.1.1
  dropdown_button2: ^2.3.9
  lorem_gen: ^2.0.1
  cached_network_image: ^3.4.1
  u_credit_card: ^1.4.0
  dotted_border: ^2.1.0
  jiffy: any
  toastification: ^2.3.0
  cherry_toast: ^1.11.0
  timeline_tile: ^2.0.0
  the_country_number: ^0.9.2+7
  flutter_libphonenumber: ^2.5.0
  mask_text_input_formatter: ^2.9.0
  font_awesome_flutter: ^10.8.0
  credit_card_validator: ^2.1.0
  localstore: ^1.4.0
  dart_mappable: ^4.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  dart_mappable_builder:  ^4.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Upayza_icon.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Font/Nexa Bold.otf
        - asset: assets/fonts/Nexa-Font/Nexa Light.otf
        - asset: assets/fonts/Nexa-Font/Nexa regular.otf
    - family: Radikal
      fonts:
        - asset: assets/fonts/Radikal/Radikal Bold.otf
        - asset: assets/fonts/Radikal/Radikal-Regular.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en
  arb_dir: lib/src/core/i18n/l10n
  output_dir: lib/src/core/i18n
